### ISSUE TITLE
Copy images to clipboard

### ISSUE THREAD

**Issue by gabrielwhite** [alfredapp/thumbnail-navigation-workflow#1]
### Feature details

It would be great if I could choose to copy the selected image to the clipboard rather than opening the file. My workflow is typically take screenshot (multiple)  ▶︎ use screenshot in another application (email, presentation, etc), so opening the file is an extra step. Thank you!

**Comment by vitorgalvao** [comment]
That is a very specific request for a workflow not geared towards screenshots. It is thus out of scope, but you can make it yourself quite easily.

1. Create a new workflow.
2. Add a [File Action Trigger](https://www.alfredapp.com/help/workflows/triggers/file-action/).
    2.1. Make the types `+public.image`.
3. Connect the `Copy Image to Clipboard` [Automation Task](https://www.alfredapp.com/help/workflows/automations/automation-task/).

You’re done. Now when using the workflow, you can use the [Universal Action](https://www.alfredapp.com/help/features/universal-actions/) to copy images to the clipboard.

See the [Getting Started Guide](https://www.alfredapp.com/help/workflows/#guides) for an interactive tutorial on making a workflow. There is [comprehensive documentation on the website](https://www.alfredapp.com/help/) to follow up (tip: find help for any object fast by clicking the `(?)` icon while editing). You may also be interested in the [YouTube channel](https://www.youtube.com/@alfredapptv) or the [Simple Ideas series of forum posts](https://www.alfredforum.com/search/?q=%22Simple%20ideas:%22&author=Stephen_C&updated_after=any&sortby=newest&search_and_or=and&search_in=titles).

---

Alternatively, use the [Screenshots workflow](https://alfred.app/workflows/vitor/screenshots/).
